DATASET: './dataset/MyStyle'
DATASET_SMOOTH: './dataset/MyStyle/smooth'
DATASET_SMOOTH_NOISE: './dataset/MyStyle/smooth_noise'
DATA_TEMP: './dataset/seg_train_5-0.8-50'
DATA_ANIME: './dataset/trainPhoto'

INIT_G_EPOCH: 5 # 'The number of epochs for generator initialization'
EPOCH: 20 # The number of epochs to run
BATCH_SIZE: 8 # The size of batch size
SAVE_FREQ: 1 # The number of ckpt_save_freq
LOAD_OR_RESUME: "load " # choices=["load", "resume"], help='load is used for fine-tuning and resume is used to continue training.'

INIT_G_LR: 0.0002 # The generator learning rate
G_LR: 0.0001 # The generator learning rate
D_LR: 0.0001 # The discriminator learning rate

IMG_SIZE: [256, 256] # The size of image: H and W
IMG_CH: 3 # The size of image channel
SN: True # using spectral norm

CHECKPOINT_DIR: './checkpoint' # Directory name to save the checkpoints
LOG_DIR: './log' # Directory name to save training logs
SAMPLE_DIR: './sample' # Directory name to save the samples on training
